version: "3.9"

services:
  web:
    image: ${WEB_IMAGE:-anilkerai/vibes-asb-manager-web:latest}
    pull_policy: always
    container_name: asbmanager-web
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    volumes:
      - appdata:/app/App_Data

volumes:
  appdata:
